# Generated by Django 4.1 on 2023-07-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("user_tag_1", models.CharField(max_length=20, unique=True)),
                (
                    "user_tag_2",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "user_tag_3",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Userword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userword_fav", models.BooleanField(default=False)),
                ("userword_mem", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "userword",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                ("word_id", models.AutoField(primary_key=True, serialize=False)),
                ("word_jap", models.CharField(max_length=20)),
                ("word_kor", models.CharField(max_length=20)),
                ("word_def", models.CharField(max_length=100)),
                ("word_tag", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "word",
                "managed": False,
            },
        ),
    ]
